#!/bin/bash

# This script does require sudo since it moves the script
# that runs lp into the bin folder.


RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'

cp lp /bin/
if [ $? == 1 ]; then
  echo ""
  echo -e "${RED}Please run this script as sudo${NC}"
  echo ""
  exit
fi
echo ""
echo -e "${GREEN}lp has been installed${NC}"
echo "Usage:"
echo -e "\t lp [user] [host] [ticket]"
echo ""	
